import sys
from unittest import TestCase

from collection.simple_document import SimpleDocument
from parameters.parameters import Parameters

__author__ = 'Saeid Balaneshin-kordan'
__email__ = "saeid@wayne.edu"
__date__ = 11 / 21 / 16


class TestSimpleDocument(TestCase):
    def setUp(self):
        self.parameters = Parameters()
        self.parameters.params["repo_dir"] = '/scratch/index/indri_5_7/ap8889'

        self.doc_words = ['pride', 'prejudice', 'novel', 'jane', 'austen', 'published', 'story', 'charts', 'emotional',
                          'development', 'protagonist', 'elizabeth', 'bennet', 'learns', 'error', 'making', 'hasty',
                          'judgements', 'comes', 'appreciate', 'difference', 'superficial', 'essential', 'comedy',
                          'writing', 'lies', 'depiction', 'manners', 'education', 'marriage', 'money', 'british',
                          'regency', 'bennet', 'estate', 'daughters', 'property', 'entailed', 'meaning', 'girls',
                          'inherit', 'married', 'woman', 'fortune', 'imperative', 'girls', 'marries', 'order',
                          'support', 'death', 'jane', 'austen', 'opening', 'line', 'truth', 'universally',
                          'acknowledged', 'single', 'man', 'possession', 'good', 'fortune', 'wife', 'sentence',
                          'filled', 'irony', 'playfulness', 'novel', 'revolves', 'necessity', 'marrying', 'love',
                          'simply', 'mercenary', 'reasons', 'despite', 'social', 'pressures', 'make', 'good', 'wealthy',
                          'match', 'pride', 'prejudice', 'retains', 'fascination', 'modern', 'readers', 'consistently',
                          'appearing', 'near', 'top', 'lists', 'loved', 'books', 'literary', 'scholars', 'general',
                          'public', 'popular', 'novels', 'english', 'literature', 'million', 'copies', 'sold', 'paved',
                          'way', 'specify', 'archetypes', 'abound', 'modern', 'literature', 'continuing', 'interest',
                          'book', 'resulted', 'number', 'dramatic', 'adaptations', 'abundance', 'novels', 'stories',
                          'imitating', 'austen', 'memorable', 'characters', 'themes', 'article', 'plot', 'summary',
                          'long', 'excessively', 'detailed', 'please', 'help', 'improve', 'removing', 'unnecessary',
                          'details', 'making', 'concise', 'september', 'learn', 'remove', 'template', 'message',
                          'novel', 'opens', 'bennet', 'trying', 'persuade', 'bennet', 'visit', 'eligible', 'bachelor',
                          'arrived', 'neighborhood', 'verbal', 'sparring', 'bennet', 'baiting', 'wife', 'transpires',
                          'visit', 'taken', 'place', 'rented', 'house', 'visit', 'followed', 'invitation', 'ball',
                          'local', 'assembly', 'rooms', 'neighborhood', 'attend', 'ball', 'open', 'cheerful', 'popular',
                          'guests', 'appears', 'attracted', 'beautiful', 'miss', 'bennet', 'friend', 'darcy', 'reputed',
                          'twice', 'wealthy', 'haughty', 'aloof', 'declines', 'dance', 'elizabeth', 'suggesting',
                          'pretty', 'tempt', 'finds', 'amusing', 'jokes', 'statement', 'friends', 'miss', 'jane',
                          'bennet', 'attracts', 'attention', 'sister', 'caroline', 'invites', 'visit', 'jane', 'visits',
                          'miss', 'caught', 'rain', 'shower', 'way', 'catching', 'serious', 'cold', 'elizabeth',
                          'genuine', 'concern', 'sister', 'visits', 'sister', 'point', 'darcy', 'begins', 'attraction',
                          'elizabeth', 'miss', 'jealous', 'elizabeth', 'wants', 'marry', 'darcy', 'illustration',
                          'hugh', 'thomson', 'representing', 'collins', 'protesting', 'reads', 'novels', 'collins',
                          'cousin', 'bennet', 'heir', 'estate', 'visits', 'bennet', 'family', 'pompous', 'obsequious',
                          'clergyman', 'expects', 'bennet', 'girls', 'wish', 'marry', 'due', 'inheritance', 'plans',
                          'propose', 'elizabeth', 'jane', 'led', 'believe', 'jane', 'taken', 'elizabeth', 'family',
                          'meet', 'dashing', 'charming', 'wickham', 'singles', 'elizabeth', 'tells', 'story',
                          'hardship', 'darcy', 'caused', 'depriving', 'living', 'position', 'clergyman', 'prosperous',
                          'parish', 'good', 'revenue', 'granted', 'life', 'promised', 'darcy', 'late', 'father',
                          'elizabeth', 'dislike', 'darcy', 'confirmed', 'ball', 'wickham', 'present', 'elizabeth',
                          'dances', 'darcy', 'jane', 'elizabeth', 'members', 'bennet', 'family', 'show', 'lack',
                          'decorum', 'bennet', 'states', 'loudly', 'expects', 'jane', 'engaged', 'member', 'family',
                          'exposes', 'ridicule', 'following', 'morning', 'collins', 'proposes', 'elizabeth', 'rejects',
                          'fury', 'mother', 'relief', 'father', 'receive', 'news', 'leaving', 'london', 'collins',
                          'proposed', 'charlotte', 'lucas', 'sensible', 'lady', 'elizabeth', 'friend', 'slightly',
                          'older', 'grateful', 'receive', 'proposal', 'guarantee', 'home', 'elizabeth', 'aghast',
                          'pragmatism', 'matters', 'love', 'jane', 'goes', 'visit', 'aunt', 'uncle', 'gardiner',
                          'unfashionable', 'address', 'london', 'miss', 'clearly', 'continue', 'friendship', 'jane',
                          'upset', 'composed', 'spring', 'elizabeth', 'visits', 'charlotte', 'collins', 'kent',
                          'elizabeth', 'hosts', 'frequently', 'invited', 'rosings', 'park', 'imposing', 'home', 'lady',
                          'catherine', 'lady', 'catherine', 'darcy', 'aunt', 'extremely', 'wealthy', 'expects', 'darcy',
                          'marry', 'daughter', 'darcy', 'cousin', 'colonel', 'fitzwilliam', 'visit', 'lady',
                          'catherine', 'colonel', 'fitzwilliam', 'tells', 'elizabeth', 'darcy', 'managed', 'friend',
                          'bad', 'match', 'convincing', 'friend', 'lady', 'indifference', 'elizabeth', 'horrified',
                          'darcy', 'involvement', 'affair', 'caused', 'sister', 'pain', 'darcy', 'fallen', 'love',
                          'elizabeth', 'proposes', 'rejects', 'stating', 'love', 'man', 'caused', 'sister',
                          'unhappiness', 'accuses', 'treating', 'wickham', 'unjustly', 'darcy', 'accuses', 'family',
                          'wanting', 'propriety', 'suggests', 'kinder', 'furious', 'part', 'barely', 'speaking',
                          'following', 'morning', 'darcy', 'gives', 'elizabeth', 'letter', 'explains', 'treatment',
                          'wickham', 'caused', 'fact', 'wickham', 'refused', 'living', 'compensated', 'economically',
                          'proceeded', 'waste', 'money', 'impoverished', 'demanded', 'living', 'threats', 'refused',
                          'tried', 'elope', 'darcy', 'old', 'sister', 'georgiana', 'great', 'dowry', 'colonel',
                          'fitzwilliam', 'attest', 'claimed', 'believed', 'miss', 'bennet', 'despite', 'amiability',
                          'actually', 'bit', 'reserved', 'love', 'darcy', 'apologises', 'hurting', 'jane', 'elizabeth',
                          'begins', 'rejudge', 'darcy', 'clearer', 'basis', 'elizabeth', 'tells', 'father', 'darcy',
                          'responsible', 'uniting', 'lydia', 'wickham', 'two', 'earliest', 'illustrations', 'pride',
                          'prejudice', 'clothing', 'styles', 'reflect', 'time', 'illustration', 'engraved', 'time',
                          'novel', 'written', 'set', 'months', 'later', 'elizabeth', 'aunt', 'uncle', 'gardiner',
                          'visit', 'darcy', 'estate', 'derbyshire', 'elizabeth', 'hears', 'account', 'housekeeper',
                          'generous', 'darcy', 'returns', 'unexpectedly', 'overwhelmingly', 'civil', 'invites',
                          'elizabeth', 'gardiner', 'meet', 'sister', 'fishing', 'elizabeth', 'surprised', 'delighted',
                          'kindness', 'aunt', 'uncle', 'suddenly', 'news', 'sister', 'lydia', 'eloped', 'wickham',
                          'tells', 'darcy', 'immediately', 'departs', 'haste', 'believing', 'lydia', 'disgrace', 'ruin',
                          'family', 'good', 'name', 'agonizing', 'wait', 'wickham', 'persuaded', 'marry', 'lydia',
                          'payment', 'debts', 'required', 'degree', 'decency', 'restored', 'lydia', 'visits',
                          'elizabeth', 'tells', 'darcy', 'wedding', 'gardiner', 'informs', 'elizabeth', 'darcy', 'made',
                          'match', 'hints', 'motive', 'point', 'darcy', 'return', 'proposes', 'jane', 'accepted',
                          'delight', 'lady', 'catherine', 'visits', 'elizabeth', 'impression', 'going', 'marry',
                          'darcy', 'elizabeth', 'refuses', 'deny', 'claim', 'lady', 'catherine', 'leaves', 'outraged',
                          'perceived', 'insolence', 'darcy', 'elizabeth', 'walk', 'engaged', 'elizabeth', 'convince',
                          'father', 'marrying', 'money', 'speaks', 'darcy', 'true', 'worth', 'happy', 'wedding',
                          'elizabeth', 'darcy', 'hugh', 'thomson', 'elizabeth', 'bennet', 'edit', 'elizabeth', 'darcy',
                          'bennet', 'reader', 'sees', 'unfolding', 'plot', 'characters', 'viewpoint', 'second',
                          'bennet', 'daughters', 'twenty', 'years', 'old', 'intelligent', 'lively', 'playful',
                          'attractive', 'witty', 'tendency', 'judge', 'impression', 'prejudice', 'title', 'selective',
                          'evidence', 'bases', 'judgments', 'plot', 'begins', 'closest', 'relationships', 'father',
                          'sister', 'jane', 'aunt', 'gardiner', 'best', 'friend', 'charlotte', 'lucas', 'story',
                          'progresses', 'relationship', 'darcy', 'course', 'elizabeth', 'darcy', 'relationship',
                          'ultimately', 'decided', 'darcy', 'overcomes', 'pride', 'elizabeth', 'overcomes', 'prejudice',
                          'leading', 'surrender', 'love', 'fitzwilliam', 'darcy', 'edit', 'fitzwilliam', 'darcy',
                          'esquire', 'initially', 'presented', 'wealthy', 'friend', 'newcomer', 'village', 'ultimately',
                          'elizabeth', 'bennet', 'love', 'interest', 'darcy', 'twenty', 'eight', 'old', 'wealthy',
                          'owner', 'renowned', 'family', 'estate', 'derbyshire', 'rumoured', 'worth', 'least',
                          'equivalent', 'usd', 'million', 'million', 'usd', 'depending', 'method', 'calculation',
                          'income', 'put', 'wealthiest', 'families', 'country', 'time', 'meaning', 'inheritance',
                          'family', 'accumulated', 'fortune', 'totals', 'minimum', 'likewise', 'inheritance', 'totals',
                          'giving', 'interest', 'handsome', 'tall', 'intelligent', 'darcy', 'lacks', 'ease', 'social',
                          'graces', 'comes', 'naturally', 'closest', 'friend', 'charles', 'cousin', 'colonel',
                          'fitzwilliam', 'former', 'childhood', 'friend', 'turned', 'antagonist', 'george', 'wickham',
                          'abuses', 'frequently', 'mistake', 'aloof', 'decorum', 'rectitude', 'proof', 'excessive',
                          'pride', 'part', 'considered', 'pride', 'title', 'makes', 'poor', 'impression', 'strangers',
                          'landed', 'gentry', 'darcy', 'greatly', 'valued', 'know', 'novel', 'progresses', 'darcy',
                          'elizabeth', 'repeatedly', 'forced', 'company', 'resulting', 'altering', 'feelings', 'better',
                          'acquaintance', 'changes', 'environment', 'end', 'work', 'overcome', 'differences',
                          'impressions', 'fall', 'love', 'bennet', 'edit', 'bennet', 'esquire', 'late', 'middle',
                          'aged', 'landed', 'gentleman', 'modest', 'income', 'annum', 'patriarch', 'dwindling',
                          'bennet', 'family', 'family', 'hertfordshire', 'landed', 'gentry', 'five', 'unmarried',
                          'daughters', 'beginning', 'story', 'jane', 'elizabeth', 'lizzy', 'eliza', 'mary', 'catherine',
                          'kitty', 'lydia', 'bennet', 'bennet', 'described', 'appearance', 'book', 'odd', 'mixture',
                          'quick', 'parts', 'sarcastic', 'humour', 'reserve', 'caprice', 'experience', 'three',
                          'twenty', 'years', 'insufficient', 'make', 'wife', 'understand', 'character', 'ironic',
                          'sarcastic', 'cynical', 'sense', 'humour', 'irritates', 'wife', 'indolent', 'parenting',
                          'style', 'manners', 'suggested', 'questionable', 'times', 'novel', 'loves', 'daughters',
                          'elizabeth', 'particular', 'ultimately', 'bennet', 'blames', 'insufficiently', 'disciplining',
                          'daughters', 'ultimately', 'enabled', 'lydia', 'run', 'away', 'wickham', 'resent',
                          'elizabeth', 'advised', 'letting', 'lydia', 'brighton', 'colonel', 'forster', 'regiment',
                          'newly', 'married', 'forster', 'particular', 'friend', 'place', 'bennet', 'possesses',
                          'inherited', 'property', 'estate', 'estate', 'entailed', 'pass', 'male', 'heirs', 'bennet',
                          'daughters', 'inherit', 'estate', 'death', 'addition', 'allowed', 'income', 'spent',
                          'frivolously', 'wife', 'failed', 'put', 'aside', 'money', 'daughters', 'dowries', 'five',
                          'daughters', 'left', 'death', 'share', 'mother', 'dowry', 'bennet', 'current', 'heir',
                          'presumptive', 'distant', 'second', 'cousin', 'sorts', 'william', 'collins', 'son', 'late',
                          'distant', 'cousin', 'bennet', 'later', 'story', 'volume', 'chapter', 'revealed', 'narrator',
                          'bennet', 'married', 'wife', 'based', 'initial', 'superficial', 'attraction', 'bennet',
                          'captivated', 'youth', 'beauty', 'appearance', 'good', 'humour', 'youth', 'beauty',
                          'generally', 'give', 'married', 'woman', 'weak', 'understanding', 'illiberal', 'mind',
                          'early', 'marriage', 'put', 'end', 'real', 'affection', 'respect', 'esteem', 'confidence',
                          'vanished', 'views', 'domestic', 'happiness', 'overthrown', 'bennet', 'disposition', 'seek',
                          'comfort', 'disappointment', 'imprudence', 'brought', 'pleasures', 'console', 'unfortunate',
                          'folly', 'vice', 'safe', 'say', 'speaks', 'living', 'making', 'sport', 'neighbours',
                          'laughing', 'turn', 'saying', 'folly', 'married', 'bennet', 'place', 'bennet', 'edit',
                          'bennet', 'gardiner', 'middle', 'aged', 'wife', 'social', 'superior', 'bennet', 'mother',
                          'five', 'daughters', 'jane', 'elizabeth', 'lizzy', 'eliza', 'mary', 'catherine', 'kitty',
                          'lydia', 'bennet', 'bennet', 'shameless', 'childish', 'frivolous', 'excitable',
                          'temperamental', 'officious', 'greedy', 'grasping', 'illogical', 'loquacious', 'invasive',
                          'artless', 'attention', 'seeking', 'hypochondriac', 'imagines', 'susceptible', 'attacks',
                          'tremors', 'palpitations', 'poor', 'nerves', 'displeased', 'things', 'going', 'way', 'child',
                          'emotionally', 'adult', 'body', 'public', 'manners', 'social', 'climbing', 'source',
                          'constant', 'embarrassment', 'jane', 'elizabeth', 'pastimes', 'shopping', 'socializing',
                          'gossiping', 'boasting', 'favourite', 'daughter', 'youngest', 'lydia', 'takes', 'younger',
                          'self', 'values', 'eldest', 'jane', 'jane', 'great', 'physical', 'beauty', 'considers',
                          'jane', 'feelings', 'virtue', 'reputation', 'least', 'favourite', 'daughter', 'elizabeth',
                          'closely', 'followed', 'mary', 'understand', 'main', 'ambition', 'life', 'marry', 'daughters',
                          'wealthy', 'men', 'matches', 'give', 'daughters', 'happiness', 'concern', 'jane', 'bennet',
                          'edit', 'letter', 'cassandra', 'dated', 'jane', 'austen', 'describes', 'picture', 'gallery',
                          'good', 'likeness', 'jane', 'bennet', 'deirdre', 'faye', 'world', 'novels', 'suggests',
                          'portrait', 'picture', 'austen', 'referring', 'jane', 'bennet', 'eldest', 'bennet', 'sister',
                          'twenty', 'two', 'years', 'old', 'novel', 'begins', 'considered', 'beautiful', 'young',
                          'lady', 'character', 'contrasted', 'elizabeth', 'sweeter', 'shyer', 'equally', 'sensible',
                          'clever', 'notable', 'trait', 'desire', 'good', 'anna', 'quindlen', 'wrote', 'jane', 'sugar',
                          'elizabeth', 'lemonade', 'jane', 'closest', 'elizabeth', 'character', 'contrasted',
                          'elizabeth', 'falls', 'love', 'charles', 'rich', 'young', 'gentleman', 'recently', 'moved',
                          'hertfordshire', 'close', 'friend', 'darcy', 'love', 'initially', 'thwarted', 'darcy',
                          'caroline', 'concerned', 'jane', 'low', 'situation', 'society', 'plans', 'darcy', 'aided',
                          'elizabeth', 'eventually', 'sees', 'error', 'ways', 'instrumental', 'bringing', 'jane',
                          'back', 'mary', 'bennet', 'edit', 'mary', 'bennet', 'plain', 'bennet', 'sister', 'join',
                          'family', 'activities', 'reads', 'plays', 'music', 'impatient', 'display', 'accomplishments',
                          'vain', 'work', 'hard', 'knowledge', 'accomplishment', 'genius', 'taste', 'two', 'younger',
                          'sisters', 'kitty', 'lydia', 'silly', 'bennet', 'mary', 'intelligent', 'thinks', 'wise',
                          'collins', 'refused', 'elizabeth', 'bennet', 'hopes', 'mary', 'prevailed', 'accept', 'led',
                          'believe', 'mary', 'hopes', 'direction', 'knows', 'engaged', 'charlotte', 'lucas', 'time',
                          'mary', 'appear', 'novel', 'sister', 'elizabeth', 'bennet', 'prefers', 'reason', 'feel',
                          'james', 'edward', 'austen', 'leigh', 'memoir', 'jane', 'austen', 'mary', 'ended', 'marrying',
                          'uncle', 'philips', 'law', 'clerks', 'name', 'mentioned', 'moving', 'catherine', 'bennet',
                          'edit', 'catherine', 'kitty', 'bennet', 'fourth', 'daughter', 'years', 'old', 'older',
                          'lydia', 'shadow', 'follows', 'pursuits', 'officers', 'regiment', 'appears', 'portrayed',
                          'envious', 'lydia', 'silly', 'young', 'woman', 'improved', 'end', 'novel', 'james', 'edward',
                          'austen', 'leigh', 'memoir', 'jane', 'austen', 'kitty', 'later', 'married', 'clergyman',
                          'name', 'mentioned', 'lived', 'near', 'derbyshire', 'lydia', 'bennet', 'edit', 'lydia',
                          'wickham', 'bennet', 'youngest', 'bennet', 'sister', 'aged', 'novel', 'begins', 'frivolous',
                          'headstrong', 'main', 'activity', 'life', 'socializing', 'especially', 'flirting', 'officers',
                          'militia', 'leads', 'running', 'george', 'wickham', 'intention', 'marrying', 'dominates',
                          'older', 'sister', 'kitty', 'supported', 'family', 'mother', 'lydia', 'shows', 'regard',
                          'moral', 'code', 'society', 'ashley', 'tauchert', 'says', 'lydia', 'feels', 'reasoning',
                          'feels', 'remorse', 'disgrace', 'causes', 'family', 'charles', 'edit', 'charles', 'esquire',
                          'handsome', 'affable', 'amiable', 'good', 'natured', 'wealthy', 'young', 'gentleman',
                          'nouveau', 'riche', 'years', 'old', 'beginning', 'novel', 'leases', 'park', 'estate', 'miles',
                          'hopes', 'purchasing', 'respectable', 'family', 'roots', 'north', 'england', 'entire',
                          'fortune', 'derived', 'trade', 'charles', 'late', 'father', 'wished', 'purchase', 'estate',
                          'order', 'raise', 'family', 'ranks', 'gentry', 'died', 'son', 'charles', 'inheriting',
                          'father', 'fortune', 'giving', 'income', 'annum', 'interest', 'seeks', 'make', 'wish',
                          'reality', 'buying', 'country', 'manor', 'surrounding', 'estate', 'beginning', 'novel',
                          'charles', 'leasing', 'park', 'hope', 'prove', 'perfect', 'plans', 'contrasted', 'friend',
                          'darcy', 'charming', 'generally', 'pleasing', 'manners', 'clever', 'experienced', 'lacks',
                          'resolve', 'easily', 'influenced', 'practically', 'led', 'nose', 'sisters', 'two', 'sisters',
                          'miss', 'caroline', 'louisa', 'hurst', 'disapprove', 'growing', 'affection', 'miss', 'jane',
                          'bennet', 'caroline', 'edit', 'caroline', 'vainglorious', 'snobbish', 'sister', 'charles',
                          'dowry', 'giving', 'additional', 'interest', 'annum', 'inheritance', 'miss', 'harbours',
                          'designs', 'darcy', 'jealous', 'growing', 'attachment', 'elizabeth', 'attempts', 'dissuade',
                          'darcy', 'liking', 'elizabeth', 'ridiculing', 'bennet', 'family', 'criticising', 'elizabeth',
                          'comportment', 'miss', 'disapproves', 'brother', 'esteem', 'jane', 'bennet', 'acknowledged',
                          'later', 'darcy', 'agreement', 'attempted', 'separate', 'couple', 'attempting', 'dissuade',
                          'jane', 'attachment', 'concealing', 'brother', 'jane', 'presence', 'london', 'jane',
                          'determined', 'find', 'fault', 'finally', 'forced', 'admit', 'deceived', 'thinking',
                          'genuine', 'friendship', 'caroline', 'realisation', 'relays', 'elizabeth', 'letter',
                          'described', 'novel', 'sister', 'fine', 'women', 'air', 'decided', 'fashion', 'disdainful',
                          'society', 'hertfordshire', 'louisa', 'caroline', 'behaviour', 'assembly', 'calculated',
                          'please', 'general', 'quickness', 'observation', 'temper', 'sister', 'judgment', 'unassailed',
                          'attention', 'disposed', 'approve', 'fact', 'fine', 'ladies', 'deficient', 'good', 'humour',
                          'pleased', 'power', 'agreeable', 'chose', 'proud', 'conceited', 'handsome', 'educated',
                          'private', 'seminaries', 'town', 'fortune', 'habit', 'spending', 'associating', 'people',
                          'rank', 'respect', 'entitled', 'think', 'respectable', 'family', 'north', 'england',
                          'circumstance', 'deeply', 'impressed', 'memories', 'brother', 'fortune', 'acquired', 'trade',
                          'george', 'wickham', 'edit', 'george', 'wickham', 'acquainted', 'darcy', 'infancy', 'son',
                          'darcy', 'father', 'steward', 'officer', 'militia', 'superficially', 'charming', 'rapidly',
                          'forms', 'attachment', 'elizabeth', 'bennet', 'spreads', 'tales', 'wrongs', 'darcy', 'done',
                          'adding', 'local', 'society', 'prejudice', 'eventually', 'found', 'wrongdoer', 'runs',
                          'lydia', 'intention', 'marrying', 'resulted', 'complete', 'disgrace', 'darcy', 'intervention',
                          'bribe', 'wickham', 'marry', 'paying', 'immediate', 'debts', 'william', 'collins', 'edit',
                          'article', 'contain', 'excessive', 'amount', 'intricate', 'detail', 'interest', 'specific',
                          'audience', 'please', 'help', 'spinning', 'relocating', 'relevant', 'information', 'removing',
                          'excessive', 'detail', 'inclusion', 'policy', 'january', 'learn', 'remove', 'template',
                          'message', 'rev', 'william', 'collins', 'aged', 'years', 'old', 'novel', 'begins', 'bennet',
                          'distant', 'second', 'cousin', 'clergyman', 'current', 'heir', 'presumptive', 'estate',
                          'house', 'physical', 'appearance', 'described', 'tall', 'heavy', 'looking', 'young', 'man',
                          'five', 'twenty', 'air', 'grave', 'stately', 'manners', 'formal', 'born', 'father', 'collins',
                          'deceased', 'described', 'illiterate', 'miserly', 'father', 'subjection', 'father', 'brought',
                          'originally', 'given', 'great', 'humility', 'manner', 'characteristic', 'good', 'deal',
                          'counteracted', 'self', 'conceit', 'weak', 'head', 'replaced', 'arrogance', 'vanity', 'due',
                          'early', 'unexpected', 'prosperity', 'early', 'prosperity', 'come', 'chance', 'hands', 'lady',
                          'catherine', 'vacancy', 'arose', 'living', 'parish', 'respect', 'felt', 'high', 'rank',
                          'veneration', 'mingling', 'good', 'opinion', 'authority', 'clergyman', 'rights', 'rector',
                          'made', 'altogether', 'mixture', 'pride', 'obsequiousness', 'self', 'importance', 'humility',
                          'conceited', 'pompous', 'narrow', 'minded', 'silly', 'man', 'elizabeth', 'rejection',
                          'collins', 'marriage', 'proposal', 'welcomed', 'father', 'regardless', 'financial', 'benefit',
                          'family', 'match', 'collins', 'marries', 'elizabeth', 'friend', 'charlotte', 'lucas',
                          'collins', 'usually', 'considered', 'foil', 'darcy', 'grave', 'serious', 'acts', 'propriety',
                          'times', 'hand', 'collins', 'acts', 'impropriety', 'exaggerated', 'humility', 'offers',
                          'comedic', 'relief', 'lady', 'catherine', 'edit', 'lady', 'catherine', 'elizabeth', 'brock',
                          'lady', 'catherine', 'confronts', 'elizabeth', 'darcy', 'title', 'page', 'illustrated',
                          'edition', 'two', 'illustrations', 'novel', 'lady', 'catherine', 'fitzwilliam', 'daughter',
                          'sister', 'earl', 'widow', 'sir', 'lewis', 'knight', 'baronet', 'rosings', 'park', 'kent',
                          'daughter', 'miss', 'anne', 'possesses', 'wealth', 'social', 'standing', 'birth', 'marriage',
                          'haughty', 'pompous', 'domineering', 'condescending', 'manner', 'entirely', 'proper',
                          'admirable', 'collins', 'example', 'admire', 'characteristics', 'deferring', 'opinions',
                          'desires', 'likes', 'distinction', 'rank', 'preserved', 'elizabeth', 'contrast', 'duly',
                          'respectful', 'intimidated', 'lady', 'catherine', 'nephew', 'darcy', 'embarrassed', 'lack',
                          'manners', 'especially', 'elizabeth', 'later', 'courts', 'disapproval', 'marrying',
                          'elizabeth', 'spite', 'numerous', 'objections', 'lady', 'catherine', 'long', 'planned',
                          'marry', 'sickly', 'daughter', 'anne', 'darcy', 'unite', 'two', 'great', 'estates',
                          'claiming', 'dearest', 'wish', 'late', 'sister', 'lady', 'anne', 'darcy', 'fitzwilliam',
                          'gardiner', 'edit', 'gardiner', 'edward', 'gardiner', 'bennet', 'brother', 'successful',
                          'tradesman', 'sensible', 'gentlemanly', 'character', 'aunt', 'gardiner', 'name', 'revealed',
                          'hinted', 'letter', 'wrote', 'elizabeth', 'signs', 'gardiner', 'close', 'nieces', 'jane',
                          'elizabeth', 'jane', 'stays', 'gardiners', 'london', 'period', 'elizabeth', 'travels',
                          'derbyshire', 'meets', 'darcy', 'gardiners', 'quick', 'perception', 'attachment', 'elizabeth',
                          'darcy', 'judge', 'prejudice', 'actively', 'involved', 'helping', 'darcy', 'arrange',
                          'marriage', 'lydia', 'wickham', 'georgiana', 'darcy', 'edit', 'georgiana', 'darcy', 'darcy',
                          'quiet', 'amiable', 'shy', 'younger', 'sister', 'dowry', 'giving', 'additional', 'interest',
                          'annum', 'inheritance', 'aged', 'barely', 'years', 'old', 'story', 'begins', 'miss', 'darcy',
                          'eloped', 'wickham', 'made', 'believe', 'two', 'love', 'reality', 'sought', 'dowry', 'miss',
                          'darcy', 'introduced', 'elizabeth', 'later', 'delighted', 'prospect', 'sister', 'law',
                          'georgiana', 'extremely', 'timid', 'gets', 'embarrassed', 'fairly', 'easily', 'brother',
                          'darcy', 'fitzwilliam', 'darcy', 'two', 'share', 'extremely', 'close', 'sibling', 'bond',
                          'jane', 'elizabeth', 'thanks', 'years', 'tutorage', 'masters', 'accomplished', 'piano',
                          'singing', 'playing', 'harp', 'drawing', 'modern', 'languages', 'modest', 'charlotte',
                          'lucas', 'edit', 'charlotte', 'collins', 'lucas', 'elizabeth', 'friend', 'years', 'old',
                          'past', 'prime', 'marriage', 'age', 'fears', 'burden', 'family', 'agrees', 'marry', 'collins',
                          'love', 'merely', 'days', 'previously', 'proposed', 'elizabeth', 'gain', 'financial',
                          'security', 'novel', 'stresses', 'importance', 'love', 'understanding', 'marriage',
                          'anticipated', 'success', 'elizabeth', 'darcy', 'relationship', 'austen', 'condemn',
                          'charlotte', 'decision', 'marry', 'money', 'austen', 'uses', 'lucas', 'common', 'voice',
                          'early', 'century', 'society', 'views', 'relationships', 'marriage', 'austen', 'uses',
                          'charlotte', 'convey', 'women', 'time', 'adhere', 'society', 'expectation', 'women', 'marry',
                          'love', 'convenience', 'daughter', 'sir', 'william', 'lucas', 'lady', 'lucas', 'friends',
                          'bennet', 'louisa', 'hurst', 'edit', 'louisa', 'hurst', 'older', 'sister', 'caroline',
                          'charles', 'wife', 'hurst', 'coming', 'marriage', 'dowry', 'giving', 'additional', 'interest',
                          'annum', 'inheritance', 'described', 'novel', 'sister', 'fine', 'women', 'air', 'decided',
                          'fashion', 'disdainful', 'society', 'hertfordshire', 'louisa', 'caroline', 'behaviour',
                          'assembly', 'calculated', 'please', 'general', 'quickness', 'observation', 'temper', 'sister',
                          'judgment', 'unassailed', 'attention', 'disposed', 'approve', 'fact', 'fine', 'ladies',
                          'deficient', 'good', 'humour', 'pleased', 'power', 'agreeable', 'chose', 'proud', 'conceited',
                          'handsome', 'educated', 'private', 'seminaries', 'town', 'fortune', 'habit', 'spending',
                          'associating', 'people', 'rank', 'respect', 'entitled', 'think', 'respectable', 'family',
                          'north', 'england', 'circumstance', 'deeply', 'impressed', 'memories', 'brother', 'fortune',
                          'acquired', 'trade', 'arguably', 'nicer', 'two', 'sisters', 'caroline', 'encourage',
                          'brother', 'admiration', 'jane', 'bennet', 'lack', 'connections', 'placing', 'caroline',
                          'personal', 'chances', 'social', 'advancement', 'brother', 'happiness', 'conspired',
                          'caroline', 'darcy', 'keep', 'charles', 'jane', 'hurst', 'edit', 'hurst', 'husband', 'louisa',
                          'hurst', 'brother', 'law', 'charles', 'caroline', 'described', 'man', 'fashion', 'fortune',
                          'social', 'status', 'consequences', 'elaborated', 'background', 'originally', 'trade', 'wife',
                          'sufficiently', 'large', 'fortune', 'order', 'entice', 'miss', 'louisa', 'marrying',
                          'indolent', 'man', 'drunk', 'lives', 'eat', 'sleep', 'pass', 'drunk', 'drink', 'play',
                          'cards', 'hears', 'miss', 'elizabeth', 'bennet', 'say', 'preferred', 'plain', 'dish', 'fresh',
                          'fruit', 'heavily', 'seasoned', 'ragout', 'dish', 'say', 'philips', 'edit', 'philips',
                          'attorney', 'practice', 'lives', 'inherited', 'late', 'father', 'law', 'law', 'clerks',
                          'marrying', 'boss', 'daughter', 'philips', 'gardiner', 'sister', 'bennet', 'silly',
                          'unintelligent', 'gossip', 'sister', 'bennet', 'phillips', 'inherited', 'dowry', 'father',
                          'entertains', 'nieces', 'guests', 'parlour', 'husband', 'residence', 'interrelationships',
                          'edit', 'comprehensive', 'web', 'showing', 'relationships', 'main', 'characters', 'pride',
                          'prejudice', 'major', 'themes', 'edit', 'critics', 'take', 'novel', 'title', 'starting',
                          'point', 'analysing', 'major', 'themes', 'pride', 'prejudice', 'robert', 'fox', 'cautions',
                          'reading', 'title', 'commercial', 'factors', 'played', 'role', 'selection', 'success',
                          'sense', 'sensibility', 'natural', 'bring', 'novel', 'author', 'formula', 'antithesis',
                          'alliteration', 'title', 'pointed', 'qualities', 'title', 'exclusively', 'assigned',
                          'protagonists', 'elizabeth', 'darcy', 'display', 'pride', 'prejudice', 'title', 'likely',
                          'taken', 'passage', 'fanny', 'burney', 'popular', 'novel', 'cecilia', 'novel', 'austen',
                          'known', 'admired', 'unfortunate', 'business', 'lyster', 'result', 'pride', 'prejudice',
                          'remember', 'pride', 'prejudice', 'owe', 'miseries', 'wonderfully', 'good', 'evil',
                          'balanced', 'pride', 'prejudice', 'owe', 'termination', 'original', 'major', 'theme',
                          'austen', 'work', 'importance', 'environment', 'upbringing', 'development', 'young', 'people',
                          'character', 'morality', 'social', 'standing', 'wealth', 'necessarily', 'advantages', 'world',
                          'theme', 'common', 'austen', 'work', 'ineffectual', 'parents', 'pride', 'prejudice',
                          'failure', 'bennet', 'parents', 'blamed', 'lydia', 'lack', 'moral', 'judgment', 'darcy',
                          'hand', 'taught', 'principled', 'scrupulously', 'honourable', 'proud', 'overbearing', 'kitty',
                          'rescued', 'lydia', 'bad', 'influence', 'spending', 'time', 'older', 'sisters', 'marry',
                          'improve', 'greatly', 'superior', 'society', 'american', 'novelist', 'anna', 'quindlen',
                          'observed', 'introduction', 'edition', 'austen', 'novel', 'pride', 'prejudice', 'thing',
                          'great', 'novels', 'consider', 'search', 'self', 'great', 'novel', 'teaches', 'search',
                          'surely', 'undertaken', 'drawing', 'room', 'making', 'small', 'talk', 'pursuit', 'great',
                          'white', 'whale', 'public', 'punishment', 'adultery', 'marriage', 'edit', 'opening', 'line',
                          'novel', 'announces', 'truth', 'universally', 'acknowledged', 'single', 'man', 'possession',
                          'good', 'fortune', 'wife', 'sets', 'marriage', 'central', 'subject', 'central', 'problem',
                          'novel', 'generally', 'readers', 'poised', 'question', 'single', 'men', 'fact', 'wife',
                          'desires', 'dictated', 'neighborhood', 'families', 'daughters', 'require', 'good', 'fortune',
                          'marriage', 'complex', 'social', 'activity', 'takes', 'political', 'economy', 'economy',
                          'generally', 'account', 'case', 'charlotte', 'lucas', 'example', 'success', 'marriage',
                          'lies', 'comfortable', 'economy', 'household', 'relationship', 'bennet', 'serves',
                          'illustrate', 'bad', 'marriages', 'based', 'initial', 'attraction', 'surface', 'substance',
                          'economic', 'psychological', 'bennets', 'marriage', 'example', 'youngest', 'bennet', 'lydia',
                          'come', 'enact', 'wickham', 'results', 'felicitous', 'central', 'characters', 'elizabeth',
                          'darcy', 'begin', 'novel', 'hostile', 'acquaintances', 'unlikely', 'friends', 'eventually',
                          'work', 'understand', 'marry', 'compatible', 'terms', 'personally', 'equal', 'social',
                          'status', 'remains', 'fraught', 'elizabeth', 'rejects', 'darcy', 'proposal', 'argument',
                          'marrying', 'love', 'introduced', 'elizabeth', 'accepts', 'darcy', 'proposal', 'loves',
                          'feelings', 'reciprocated', 'austen', 'complex', 'sketching', 'different', 'marriages',
                          'ultimately', 'allows', 'readers', 'question', 'forms', 'alliance', 'desirable', 'especially',
                          'comes', 'privileging', 'economic', 'sexual', 'companionate', 'attraction', 'wealth', 'edit',
                          'money', 'plays', 'key', 'role', 'marriage', 'market', 'young', 'ladies', 'seeking',
                          'husband', 'men', 'wish', 'marry', 'woman', 'means', 'two', 'examples', 'george', 'wickham',
                          'tried', 'elope', 'georgiana', 'darcy', 'colonel', 'fitzwilliam', 'marrying', 'woman', 'rich',
                          'family', 'ensured', 'linkage', 'high', 'family', 'visible', 'desires', 'sisters', 'brother',
                          'married', 'georgiana', 'darcy', 'bennet', 'encouraging', 'daughters', 'marry', 'wealthy',
                          'man', 'high', 'social', 'class', 'example', 'chapter', 'arrives', 'says', 'thinking',
                          'marrying', 'inheritance', 'descent', 'restricted', 'entailment', 'restrict', 'inheritance',
                          'male', 'heirs', 'case', 'bennet', 'family', 'collins', 'inherit', 'family', 'farm', 'bennet',
                          'death', 'proposal', 'elizabeth', 'allowed', 'share', 'refused', 'offer', 'inheritance',
                          'laws', 'benefited', 'males', 'women', 'independent', 'legal', 'rights', 'second', 'half',
                          'century', 'consequence', 'women', 'financial', 'security', 'time', 'novel', 'set',
                          'depended', 'men', 'upper', 'middle', 'aristocratic', 'classes', 'marriage', 'man',
                          'reliable', 'income', 'route', 'security', 'woman', 'future', 'children', 'ironically',
                          'text', 'opens', 'line', 'truth', 'universally', 'acknowledged', 'single', 'man',
                          'possession', 'good', 'fortune', 'wife', 'ironic', 'generally', 'society', 'woman', 'looking',
                          'wealthy', 'husband', 'order', 'prosperous', 'life', 'class', 'edit', 'austen', 'known',
                          'romances', 'marriages', 'take', 'place', 'novels', 'engage', 'form', 'economic', 'concerns',
                          'involved', 'matches', 'pride', 'prejudice', 'darcy', 'proposes', 'elizabeth', 'cites',
                          'economic', 'social', 'differences', 'obstacle', 'excessive', 'love', 'overcome', 'anxiously',
                          'harps', 'problems', 'poses', 'social', 'circle', 'aunt', 'lady', 'catherine', 'later',
                          'characterizes', 'differences', 'particularly', 'harsh', 'terms', 'conveys', 'elizabeth',
                          'marriage', 'darcy', 'shades', 'polluted', 'elizabeth', 'responds', 'lady', 'catherine',
                          'accusations', 'potentially', 'contaminating', 'economic', 'social', 'position', 'elizabeth',
                          'insists', 'darcy', 'equals', 'lady', 'catherine', 'refuses', 'accept', 'darcy', 'actual',
                          'marriage', 'elizabeth', 'novel', 'closes', 'present', 'particular', 'problem', 'navigating',
                          'social', 'class', 'caroline', 'hurst', 'behave', 'speak', 'belonged', 'upper', 'echelons',
                          'society', 'austen', 'makes', 'point', 'explain', 'acquired', 'wealth', 'trade', 'gentry',
                          'aristocracy', 'methods', 'inheriting', 'estates', 'making', 'money', 'tenants', 'landlords',
                          'fact', 'rents', 'hall', 'distinguishes', 'significantly', 'darcy', 'estate', 'belonged',
                          'father', 'family', 'mother', 'grandson', 'nephew', 'earl', 'darcy', 'property', 'portable',
                          'growing', 'wealth', 'makes', 'good', 'catch', 'marriage', 'market', 'daughters', 'gentility',
                          'jane', 'bennet', 'social', 'status', 'good', 'family', 'require', 'money', 'stake', 'claim',
                          'quasi', 'aristocrats', 'class', 'plays', 'central', 'role', 'evolution', 'characters',
                          'jane', 'austen', 'radical', 'approach', 'class', 'plot', 'unfolds', 'addition',
                          'undercurrent', 'old', 'anglo', 'norman', 'upper', 'class', 'hinted', 'story', 'suggested',
                          'names', 'fitzwilliam', 'darcy', 'aunt', 'lady', 'catherine', 'fitzwilliam', 'burke',
                          'traditional', 'norman', 'surnames', 'self', 'knowledge', 'edit', 'elizabeth', 'darcy',
                          'born', 'great', 'match', 'interactions', 'critiques', 'recognise', 'faults', 'work',
                          'correct', 'elizabeth', 'meditates', 'mistakes', 'thoroughly', 'chapter', 'despicably',
                          'acted', 'cried', 'prided', 'discernment', 'valued', 'abilities', 'disdained', 'generous',
                          'sister', 'gratified', 'vanity', 'useless', 'distrust', 'humiliating', 'discovery',
                          'humiliation', 'love', 'wretchedly', 'blind', 'vanity', 'love', 'folly', 'pleased',
                          'preference', 'offended', 'neglect', 'beginning', 'acquaintance', 'courted', 'prepossession',
                          'ignorance', 'driven', 'reason', 'away', 'concerned', 'moment', 'knew', 'characters', 'type',
                          'self', 'reflection', 'capacity', 'experience', 'correct', 'tanner', 'essay', 'notes',
                          'bennet', 'particular', 'limited', 'view', 'requirements', 'performance', 'lacking',
                          'introspective', 'tendencies', 'incapable', 'appreciating', 'feelings', 'aware', 'material',
                          'objects', 'bennet', 'behaviour', 'reflects', 'society', 'lives', 'knows', 'daughters',
                          'succeed', 'married', 'business', 'life', 'daughters', 'married', 'solace', 'visiting',
                          'news', 'proves', 'bennet', 'aware', 'material', 'objects', 'feelings', 'emotions', 'style',
                          'edit', 'pride', 'prejudice', 'austen', 'works', 'employs', 'narrative', 'technique', 'free',
                          'indirect', 'speech', 'defined', 'free', 'representation', 'character', 'speech', 'means',
                          'words', 'actually', 'character', 'words', 'typify', 'character', 'thoughts', 'way',
                          'character', 'think', 'speak', 'thought', 'austen', 'creates', 'characters', 'fully',
                          'developed', 'personalities', 'unique', 'voices', 'darcy', 'bennet', 'alike', 'considerably',
                          'different', 'narrative', 'adopts', 'tone', 'vocabulary', 'particular', 'character', 'case',
                          'elizabeth', 'austen', 'invites', 'reader', 'follow', 'events', 'elizabeth', 'viewpoint',
                          'sharing', 'prejudices', 'misapprehensions', 'learning', 'curve', 'undergone', 'protagonists',
                          'disclosed', 'solely', 'elizabeth', 'point', 'view', 'free', 'indirect', 'speech',
                          'essential', 'remain', 'caught', 'stuck', 'elizabeth', 'misprisions', 'times', 'reader',
                          'allowed', 'gain', 'knowledge', 'character', 'feelings', 'letters', 'exchanged', 'novel',
                          'darcy', 'letter', 'elizabeth', 'example', 'letter', 'reader', 'elizabeth', 'given',
                          'knowledge', 'wickham', 'true', 'character', 'austen', 'known', 'irony', 'novel',
                          'especially', 'viewpoint', 'character', 'elizabeth', 'bennet', 'conveys', 'oppressive',
                          'rules', 'feminity', 'actually', 'dominate', 'life', 'work', 'covered', 'beautifully',
                          'carved', 'trojan', 'horse', 'ironic', 'distance', 'beginning', 'historical', 'investigation',
                          'development', 'particular', 'literary', 'form', 'transitioning', 'empirical',
                          'verifications', 'reveals', 'fid', 'tool', 'emerged', 'time', 'practical', 'means',
                          'addressing', 'physical', 'distinctness', 'minds', 'way', 'fid', 'distinctly', 'literary',
                          'response', 'environmental', 'concern', 'providing', 'scientific', 'justification', 'reduce',
                          'literature', 'mechanical', 'extension', 'biology', 'takes', 'value', 'original', 'form',
                          'development', 'novel', 'edit', 'page', 'letter', 'jane', 'austen', 'sister', 'cassandra',
                          'june', 'mentions', 'pride', 'prejudice', 'working', 'title', 'impressions', 'nla', 'austen',
                          'began', 'writing', 'novel', 'staying', 'park', 'kent', 'brother', 'edward', 'wife',
                          'originally', 'titled', 'impressions', 'written', 'october', 'august', 'november', 'austen',
                          'father', 'letter', 'london', 'bookseller', 'thomas', 'cadell', 'ask', 'interest',
                          'manuscript', 'offer', 'declined', 'return', 'post', 'austen', 'made', 'significant',
                          'revisions', 'manuscript', 'impressions', 'remains', 'original', 'manuscript', 'reduced',
                          'conjecture', 'large', 'number', 'letters', 'final', 'novel', 'assumed', 'impressions',
                          'epistolary', 'novel', 'later', 'renamed', 'story', 'pride', 'prejudice', 'renaming', 'novel',
                          'austen', 'probably', 'mind', 'sufferings', 'oppositions', 'final', 'chapter', 'fanny',
                          'burney', 'cecilia', 'called', 'pride', 'prejudice', 'phrase', 'appears', 'three', 'times',
                          'block', 'capitals', 'possible', 'novel', 'original', 'title', 'altered', 'avoid',
                          'confusion', 'works', 'years', 'completion', 'impressions', 'revision', 'pride', 'prejudice',
                          'two', 'works', 'published', 'name', 'novel', 'margaret', 'holford', 'comedy', 'horace',
                          'smith', 'publication', 'history', 'edit', 'title', 'page', 'edition', 'illustrated', 'brock',
                          'austen', 'sold', 'copyright', 'novel', 'thomas', 'egerton', 'military', 'library',
                          'whitehall', 'exchange', 'austen', 'asked', 'proved', 'costly', 'decision', 'austen',
                          'published', 'sense', 'sensibility', 'commission', 'basis', 'indemnified', 'publisher',
                          'losses', 'received', 'profits', 'costs', 'publisher', 'commission', 'unaware', 'sense',
                          'sensibility', 'sell', 'edition', 'making', 'passed', 'copyright', 'egerton', 'payment',
                          'meaning', 'risk', 'profits', 'jan', 'fergus', 'calculated', 'egerton', 'subsequently',
                          'made', 'two', 'editions', 'book', 'egerton', 'published', 'edition', 'pride', 'prejudice',
                          'three', 'hardcover', 'volumes', 'january', 'advertised', 'morning', 'chronicle', 'priced',
                          'favourable', 'reviews', 'edition', 'sold', 'second', 'edition', 'published', 'november',
                          'third', 'edition', 'published', 'foreign', 'language', 'translations', 'appeared', 'french',
                          'subsequent', 'translations', 'published', 'german', 'danish', 'swedish', 'pride',
                          'prejudice', 'published', 'united', 'states', 'august', 'elizabeth', 'bennet', 'pride',
                          'prejudice', 'novel', 'richard', 'bentley', 'standard', 'novel', 'series', 'chapman',
                          'scholarly', 'edition', 'pride', 'prejudice', 'published', 'standard', 'edition', 'modern',
                          'published', 'versions', 'novel', 'based', 'novel', 'originally', 'published', 'austen',
                          'name', 'written', 'author', 'sense', 'sensibility', 'carried', 'responsibility', 'austen',
                          'sense', 'sensibility', 'released', 'written', 'lady', 'reception', 'edit', 'main', 'article',
                          'reception', 'history', 'jane', 'austen', 'publication', 'edit', 'novel', 'received', 'three',
                          'favourable', 'reviews', 'months', 'following', 'publication', 'anne', 'isabella', 'milbanke',
                          'later', 'wife', 'lord', 'byron', 'called', 'fashionable', 'novel', 'noted', 'critic',
                          'reviewer', 'george', 'henry', 'lewes', 'declared', 'written', 'pride', 'prejudice', 'tom',
                          'jones', 'waverley', 'novels', 'charlotte', 'letter', 'lewes', 'wrote', 'pride', 'prejudice',
                          'disappointment', 'carefully', 'fenced', 'highly', 'cultivated', 'garden', 'neat', 'borders',
                          'delicate', 'flowers', 'open', 'country', 'fresh', 'air', 'blue', 'hill', 'bonny', 'beck',
                          'late', 'centuries', 'edit', 'shock', 'shocks', 'joyce', 'innocent', 'grass', 'makes',
                          'uncomfortable', 'english', 'spinster', 'middle', 'class', 'describe', 'amorous', 'effects',
                          'brass', 'reveal', 'frankly', 'sobriety', 'economic', 'basis', 'society', 'auden', 'austen',
                          'bbc', 'conducted', 'poll', 'best', 'loved', 'book', 'pride', 'prejudice', 'came', 'second',
                          'lord', 'rings', 'survey', 'australian', 'readers', 'pride', 'prejudice', 'came', 'list',
                          'best', 'books', 'written', 'anniversary', 'pride', 'prejudice', 'january', 'celebrated',
                          'globe', 'media', 'networks', 'huffington', 'post', 'new', 'york', 'times', 'daily',
                          'telegraph', 'adaptations', 'edit', 'film', 'television', 'theatre', 'edit', 'jane', 'austen',
                          'popular', 'culture', 'pride', 'prejudice', 'pride', 'prejudice', 'engendered', 'numerous',
                          'adaptations', 'notable', 'film', 'versions', 'starring', 'greer', 'garson', 'laurence',
                          'olivier', 'based', 'part', 'helen', 'jerome', 'stage', 'adaptation', 'starring', 'knightley',
                          'oscar', 'nominated', 'performance', 'matthew', 'macfadyen', 'notable', 'television',
                          'versions', 'two', 'bbc', 'version', 'starring', 'elizabeth', 'david', 'popular', 'version',
                          'starring', 'jennifer', 'ehle', 'colin', 'firth', 'stage', 'version', 'created', 'helen',
                          'jerome', 'played', 'james', 'theatre', 'london', 'starring', 'celia', 'johnson', 'hugh',
                          'williams', 'impressions', 'broadway', 'musical', 'version', 'starring', 'polly', 'bergen',
                          'farley', 'granger', 'hermione', 'gingold', 'musical', 'concept', 'album', 'written',
                          'bernard', 'taylor', 'claire', 'moore', 'role', 'elizabeth', 'bennet', 'peter', 'karrie',
                          'role', 'darcy', 'new', 'stage', 'production', 'jane', 'austen', 'pride', 'prejudice', 'new',
                          'musical', 'presented', 'concert', 'october', 'rochester', 'new', 'york', 'colin', 'donnell',
                          'darcy', 'literature', 'edit', 'main', 'article', 'list', 'literary', 'adaptations', 'pride',
                          'prejudice', 'novel', 'inspired', 'number', 'works', 'direct', 'adaptations', 'books',
                          'inspired', 'pride', 'prejudice', 'following', 'darcy', 'daughters', 'exploits', 'adventures',
                          'miss', 'alethea', 'darcy', 'elizabeth', 'aston', 'darcy', 'story', 'best', 'seller',
                          'dialogue', 'darcy', 'janet', 'aylmer', 'pride', 'prejudice', 'continued', 'unequal',
                          'marriage', 'pride', 'prejudice', 'twenty', 'years', 'later', 'emma', 'tennant', 'book',
                          'ruth', 'helen', 'baker', 'author', 'jane', 'austen', 'ruined', 'life', 'darcy', 'broke',
                          'heart', 'beth', 'precipitation', 'continuation', 'miss', 'jane', 'austen', 'pride',
                          'prejudice', 'helen', 'baker', 'author', 'searching', 'mary', 'simonsen', 'darcy', 'takes',
                          'wife', 'sequel', 'darcy', 'elizabeth', 'nights', 'days', 'linda', 'gwyn', 'comedic',
                          'romance', 'novel', 'seducing', 'darcy', 'heroine', 'lands', 'pride', 'prejudice', 'way',
                          'magic', 'massage', 'fling', 'darcy', 'unknowingly', 'changes', 'rest', 'story', 'abigail',
                          'reynolds', 'author', 'regency', 'set', 'variations', 'pride', 'prejudice', 'variations',
                          'series', 'includes', 'darcy', 'obsession', 'conquer', 'darcy', 'darcy', 'fitzwilliam',
                          'darcy', 'man', 'world', 'modern', 'adaptation', 'man', 'loved', 'pride', 'prejudice', 'set',
                          'cape', 'cod', 'helen', 'fielding', 'novel', 'bridget', 'jones', 'diary', 'based', 'pride',
                          'prejudice', 'spawned', 'feature', 'film', 'name', 'released', 'march', 'quirk', 'books',
                          'released', 'pride', 'prejudice', 'zombies', 'takes', 'austen', 'actual', 'original', 'work',
                          'mashes', 'zombie', 'hordes', 'cannibalism', 'ninja', 'ultraviolent', 'mayhem', 'march',
                          'quirk', 'books', 'published', 'prequel', 'deals', 'elizabeth', 'bennet', 'early', 'days',
                          'zombie', 'hunter', 'pride', 'prejudice', 'zombies', 'dawn', 'dreadfuls', 'movie',
                          'aforementioned', 'contemporary', 'literature', 'adaptation', 'released', 'starring', 'lily',
                          'james', 'matt', 'smith', 'author', 'mitzi', 'expanded', 'novel', 'pride', 'prejudice',
                          'hidden', 'lusts', 'historical', 'sex', 'parody', 'parallels', 'original', 'plot', 'writing',
                          'style', 'jane', 'austen', 'marvel', 'published', 'take', 'classic', 'releasing', 'short',
                          'comic', 'series', 'five', 'issues', 'stays', 'true', 'original', 'storyline', 'issue',
                          'published', 'april', 'written', 'nancy', 'published', 'graphic', 'novel', 'artwork', 'hugo',
                          'petrus', 'pamela', 'aidan', 'author', 'trilogy', 'books', 'telling', 'story', 'pride',
                          'prejudice', 'darcy', 'point', 'view', 'fitzwilliam', 'darcy', 'gentleman', 'books',
                          'assembly', 'duty', 'desire', 'three', 'remain', 'detective', 'novel', 'author', 'james',
                          'written', 'book', 'titled', 'death', 'comes', 'murder', 'mystery', 'set', 'six', 'years',
                          'elizabeth', 'darcy', 'marriage', 'sandra', 'lerner', 'sequel', 'pride', 'prejudice',
                          'second', 'impressions', 'develops', 'story', 'imagined', 'happened', 'original', 'novel',
                          'characters', 'written', 'style', 'austen', 'extensive', 'research', 'period', 'language',
                          'published', 'pen', 'name', 'ava', 'farmer', 'baker', 'novel', 'imagines', 'lives',
                          'servants', 'pride', 'prejudice', 'curtis', 'set', 'characters', 'pride', 'prejudice',
                          'modern', 'cincinnati', 'bennet', 'parents', 'erstwhile', 'cincinnati', 'social', 'climbers',
                          'fallen', 'hard', 'times', 'elizabeth', 'successful', 'independent', 'new', 'york',
                          'journalist', 'single', 'older', 'sister', 'jane', 'intervene', 'salvage', 'family',
                          'financial', 'situation', 'unemployed', 'adult', 'sisters', 'move', 'house', 'onward', 'life',
                          'process', 'encounter', 'chip', 'young', 'doctor', 'reluctant', 'reality', 'celebrity',
                          'medical', 'school', 'classmate', 'fitzwilliam', 'darcy', 'cynical', 'neurosurgeon', 'pride',
                          'prejudice', 'inspired', 'works', 'scientific', 'writing', 'scientists', 'named', 'pheromone',
                          'identified', 'male', 'mouse', 'urine', 'darcy', 'strongly', 'attracted', 'females',
                          'scientific', 'paper', 'published', 'journal', 'inherited', 'metabolic', 'diseases',
                          'speculated', 'bennet', 'carrier', 'rare', 'genetic', 'disease', 'explaining', 'bennets',
                          'sons', 'bennet', 'sisters', 'silly']

    def test_replace_stemmed_similar_words_list(self):
        self.single_document = SimpleDocument(self.parameters)
        neighbor = ['sapiens', 'human', 'genus', 'evolutionary', 'species', 'humans', "Human", 'hominins', 'Homo',
                    'bipedal']
        res = self.single_document.replace_stemmed_similar_words_list(neighbor)
        print(res, file=sys.stderr)
        expected_res = ['sapiens', 'human', 'genus', 'evolutionary', 'species', 'human', 'human', 'hominins', 'Homo',
                        'bipedal']
        self.assertEqual(res, expected_res)

    def test_get_words(self):
        self.single_document = SimpleDocument(self.parameters)
        doc_words = self.single_document.get_words("../../configs/others/pride_and_prejudice_wiki.txt")
        print(doc_words, file=sys.stderr)
        self.assertEqual(doc_words, self.doc_words)
